// <auto-generated />
using System;
using AgroOrganizer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroOrganizer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AgroOrganizer.Models.Entities.Activity.ActivityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("FieldSeasonId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("FieldSeasonId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("AgroOrganizer.Models.Entities.Contracts.ContractEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateSigned")
                        .HasColumnType("datetime");

                    b.Property<DateTimeOffset?>("ExpirationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FieldId")
                        .IsUnique();

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("AgroOrganizer.Models.Entities.Drivers.DriverEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DriverAge")
                        .HasColumnType("int");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DriverPhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("HiredOn")
                        .HasColumnType("datetime");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("AgroOrganizer.Models.Entities.Expense.ExpenseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("FieldSeasonId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FieldSeasonId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("AgroOrganizer.Models.Entities.Field.FieldEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BoundaryJson")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("FieldLocation")
                        .HasColumnType("longtext");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FieldNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("FieldSize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("AgroOrganizer.Models.Entities.FieldSeason.FieldSeasonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CropType")
                        .HasColumnType("int");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.ToTable("FieldSeasons");
                });

            modelBuilder.Entity("AgroOrganizer.Models.Entities.Sales.SaleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BuyerName")
                        .HasColumnType("longtext");

                    b.Property<int?>("CropType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateSigned")
                        .HasColumnType("datetime");

                    b.Property<int?>("FieldSeasonId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PriceForKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("Quantity")
                        .HasColumnType("double");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FieldSeasonId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("AgroOrganizer.Models.Entities.User.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("ShouldChangePassword")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AgroOrganizer.Models.Entities.Vehicles.VehicleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastServiceDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PurchaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("AgroOrganizer.Models.Entities.Vehicles.VehicleServiceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleServices");
                });

            modelBuilder.Entity("AgroOrganizer.Models.Entities.Activity.ActivityEntity", b =>
                {
                    b.HasOne("AgroOrganizer.Models.Entities.Drivers.DriverEntity", "Driver")
                        .WithMany("Activities")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgroOrganizer.Models.Entities.FieldSeason.FieldSeasonEntity", "FieldSeason")
                        .WithMany("Activities")
                        .HasForeignKey("FieldSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("FieldSeason");
                });

            modelBuilder.Entity("AgroOrganizer.Models.Entities.Contracts.ContractEntity", b =>
                {
                    b.HasOne("AgroOrganizer.Models.Entities.Field.FieldEntity", "Field")
                        .WithOne("Contract")
                        .HasForeignKey("AgroOrganizer.Models.Entities.Contracts.ContractEntity", "FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("AgroOrganizer.Models.Entities.Expense.ExpenseEntity", b =>
                {
                    b.HasOne("AgroOrganizer.Models.Entities.FieldSeason.FieldSeasonEntity", "FieldSeason")
                        .WithMany("Expenses")
                        .HasForeignKey("FieldSeasonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("FieldSeason");
                });

            modelBuilder.Entity("AgroOrganizer.Models.Entities.Field.FieldEntity", b =>
                {
                    b.HasOne("AgroOrganizer.Models.Entities.User.UserEntity", "User")
                        .WithMany("Fields")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgroOrganizer.Models.Entities.FieldSeason.FieldSeasonEntity", b =>
                {
                    b.HasOne("AgroOrganizer.Models.Entities.Field.FieldEntity", "Field")
                        .WithMany("Seasons")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("AgroOrganizer.Models.Entities.Sales.SaleEntity", b =>
                {
                    b.HasOne("AgroOrganizer.Models.Entities.FieldSeason.FieldSeasonEntity", "FieldSeason")
                        .WithMany("Sales")
                        .HasForeignKey("FieldSeasonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("FieldSeason");
                });

            modelBuilder.Entity("AgroOrganizer.Models.Entities.Vehicles.VehicleServiceEntity", b =>
                {
                    b.HasOne("AgroOrganizer.Models.Entities.Vehicles.VehicleEntity", "Vehicle")
                        .WithMany("Services")
                        .HasForeignKey("VehicleId");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AgroOrganizer.Models.Entities.Drivers.DriverEntity", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("AgroOrganizer.Models.Entities.Field.FieldEntity", b =>
                {
                    b.Navigation("Contract");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("AgroOrganizer.Models.Entities.FieldSeason.FieldSeasonEntity", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Expenses");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("AgroOrganizer.Models.Entities.User.UserEntity", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("AgroOrganizer.Models.Entities.Vehicles.VehicleEntity", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
